In [6]:
import numpy as np
import matplotlib.pyplot as plt
def delta_kronecker(i,j):
    if i==j:
        return 1
    else:
        return 0
sum1 = 0 
sum2 = 0
n = 4
v=1
w=2
def part1(i,j,n):
    p1=0
    p2=0
    for k in range(1,2*n,2):
        p1 += delta_kronecker(i,k+1)*delta_kronecker(j,k)+delta_kronecker(j,k+1)*delta_kronecker(i,k) 
    for k in range(1,2*(n-1),2):
        p2 += delta_kronecker(i,k+2)*delta_kronecker(j,k+1)+delta_kronecker(j,k+2)*delta_kronecker(i,k+1)
    return (v*p1+w*p2)


H = np.zeros((2*n, 2*n))
for i in range(2*n):
    for j in range(2*n):
        H[i][j]= part1(i+1,j+1,n)
print(H)

[[0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 2. 0. 0. 0. 0. 0.]
 [0. 2. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 2. 0. 0. 0.]
 [0. 0. 0. 2. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 2. 0.]
 [0. 0. 0. 0. 0. 2. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]
